### ISSUE TITLE
Images not shown correctly in the pdf viewer

### ISSUE THREAD

**Issue by mtazzari** [EDP-Sciences/sharelatex#1]
Hi,
I am having the following issue:  the images are not shown correctly in the built-in pdf viewer. I attach a screenshot. 

Actually, if I use the native pdf viewer of the browser or if I download the pdf, the images are in their right place. I guess the pdf is compiled perfectly (same result as the local compilation on my laptop), but the visualization does something weird.

Could you help with this?
Thanks!

<img width="670" alt="screenshot 2016-08-03 alle 00 51 19" src="https://cloud.githubusercontent.com/assets/6020226/17348153/b92ac18c-5914-11e6-8587-1a37bfcf5d51.png">

**Comment by smeingast** [comment]
Came here to post about this. I have the same issue across multiple browsers (Safari, Chrome, Firefox)

**Comment by xtrochu** [comment]
Does this issue occur on all images (including the one in the sample document) or specific ones ?
Could-you please give me the project id of the project that trigger this bug (it's the hexadecimal sequence that follow the url http://writingstudio.aws.edpsciences.org/project/<project-id> ) ?

**Comment by mtazzari** [comment]
Hi,

the issue was occurring in substantially all the images, but with no general rule. I just checked right now, and it seems it does not occur anymore, but one should try modifying the tex, changing locations of the figures, etc.
This is the url
http://writingstudio.aws.edpsciences.org/project/57a11ce104aff8960943217b

Thanks

**Comment by xtrochu** [comment]
Thank you.

I have been unable to reproduce this issue, and it looks like it's not occuring consistently, as there has been no change to the writing studio since last september.

We are going to deploy very soon an update to the Writing Studio that includes an update of PDF.js, the library that is used to display PDF pages in the viewer mode. I hope that this update will fix permanently this issue.

**Comment by smeingast** [comment]
I am still seeing it, though I was also not able to find a pattern. Sometimes switching back and forth from the native PDF viewer resolves this, but as soon as I reload the document some images are out of place again. Two of my colleagues have the same issue and we are all using Macs (if that could be a reason).
