### ISSUE TITLE
Account settings redirect to someone else

### ISSUE THREAD

**Issue by aoberto** [EDP-Sciences/sharelatex#2]
Hello

When I am logged in and on the main page :http://writingstudio.aws.edpsciences.org/project/
I click on "Account" -> "Account settings" 
I reach this page : http://writingstudio.aws.edpsciences.org/user/settings
with a form filled with an email : clada@cfa.ahrvard.edu
and "Charles Lada" name (who is not me). 
But the orcid is really mine : 0000-0001-7141-1542

It is a bit wired, I was assuming that I will obtain my name and see which email address is used in my account, no ?
May be it is linked, but I can not see projects shared with me (maybe because the system think that I am someone else ?)

thanks a lot

**Comment by xtrochu** [comment]
Indeed, this is very surprising behaviour.
Your ORCID is the account identifier, so you can feel free to modify the names and emails in your account.

II will keep this issue open and I am going to investigate possible cause for this bug

**Comment by aoberto** [comment]
Thank you for your reply, but I can't change the information, I got the 
error "email_already_registered"

thanks a lot

**Comment by xtrochu** [comment]
Could-you please send me your account details at writing-studio@edpsciences.org ? I can fix this easily in the database.
