### ISSUE TITLE
Not able to login with ORCID, "502 Bad Gateway" error

### ISSUE THREAD

**Issue by yangcht** [EDP-Sciences/sharelatex#3]
I am unable to login the Writing Studio with my ORCID. It shows 502 Bad Gateway all the time.

**Comment by kluskaj** [comment]
I have a similar problem but a different error message:
"Oh dear, something went wrong. Something went wrong with your request, sorry. Our staff are probably looking into this, but if it continues, please contact us at writing-studio@edpsciences.org"

**Comment by edp-jlepage** [comment]
Hi,
Sorry for the late answer, we have corrected several issues since last year.
Some of them was around OrcID interconnexion.

Sorry for the inconvenience.
Do not hesitate to write at support-writingstudio@edpsciences.org in case of another issue.

Kind regards,
EDP Sciences
