### ISSUE TITLE
Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.

### ISSUE THREAD

**Issue by nflagey** [EDP-Sciences/sharelatex#4]
I wanted to start using the A&A service but it does not even seem to be able to compile ...

**Comment by edp-jlepage** [comment]
Hi,
Sorry for the late answer, we have corrected several issues lately.
Sorry for the inconvenience.

Do not hesitate to write at support-writingstudio@edpsciences.org in case of another issue.

Kind regards,
EDP Sciences
